---
- name: Copy talk source
  copy: src=../chat/ dest=/tmp/chat

- name: Install pip
  apt: name=python-pip

- name: Install python development
  apt: name=python-dev

- name: Install chat dependencies
  command: chdir=/tmp/chat pip install -r requirements.txt

- name: Copy init.d script
  copy: src=talkd dest=/etc/init.d/talkd mode=0751

- name: Start talkd
  action: service name=talkd state=started
