# Podfile

# Select the appropriate platform below
# Specify the minimum supported iOS version (or later) required by Kiwi
platform :ios, '8.0'
# platform :osx

target :Abode do

pod 'AFNetworking'
pod 'Mantle'
pod 'ReactiveCocoa'
pod 'Reachability'


end
